version: '3.3'

services:
   db:
     image: mysql:8.0
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD : admin
       MYSQL_DATABASE: mutant
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin   

   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
     restart: always
     environment:
       discovery.type: "single-node"
       ES_JAVA_OPTS: "-Xms2g -Xmx2g"
       xpack.monitoring.enabled: "true"

   app:
     depends_on:
       - db
       - elasticsearch
     build: ./
     volumes:
        - ./logs:/usr/app/logs
     ports:
       - "3000:3000"
     restart: always
     environment:
       ELASTIC_SEARCH_HOST: elasticsearch
       DB_HOST : db:3306
       DB_USER : admin
       DB_PASSWORD : admin
       DB_DATABASE : mutant
